import vine, { SimpleMessagesProvider } from '@vinejs/vine'

vine.messagesProvider = new SimpleMessagesProvider({
  'email.required': 'Email must be filled!',
  'email.email': 'Email format incorrect!',
  'email.unique': 'Email already registered!',
  'password.required': 'Password must be filled!',
  'password.minLength': 'Password must at least 8 characters!',
  'password.confirmed': 'Password confirmation failed!',
  'fullName.required': 'Full name must be filled!',
  'gender.required': 'Gender must be filled!',
  'dob.required': 'Date of birth must be filled!',
  'dob.date': 'Date of birth format incorrect!',
  'address.required': 'Address must be filled!',
  'communityName.required': 'Community name must be filled!',
  'thumbnail.required': 'Community image must be filled!',
  'thumbnail.file': 'Community image format incorrect!',
  'auctionName.required': 'Auction name must be filled!',
  'categoryId.required': 'Category must be filled!',
  'categoryId.number': 'Category must be a number!',
  'communityId.number': 'Community must be a number!',
  'description.required': 'Description must be filled!',
  'startBid.required': 'Start bid must be filled!',
  'startBid.number': 'Start bid must be a number!',
  'startBid.positive': 'Start bid must be positive number!',
  'buyNow.required': 'Buy now must be filled!',
  'buyNow.boolean': 'Buy now must be a boolean (true | false)',
  'buyNowPrice.number': 'Buy now price must be a number!',
  'buyNowPrice.positive': 'Buy now price must be positive number!',
  'timer.required': 'Timer must be filled!',
  'timer.date': 'Timer format incorrect! (DD-MM-YYYY, H:m)',
  'auctionImages.required': 'Auction image must be filled!',
  'auctionImages.array': 'Auction images must be an array!',
  'auctionImages.array.minLength': 'Auction images must at least 1 image!',
  'auctionImages.*.file': 'Auction images format incorrect!',
})
